# Generated by Django 4.0.7 on 2022-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
