# Generated by Django 4.0.7 on 2022-09-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_board_current_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='current_time',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published'),
        ),
    ]
