# Generated by Django 4.0.7 on 2022-09-24 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0011_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
