# Generated by Django 4.0.7 on 2022-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_fileupload_created_at_fileupload_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
