# Generated by Django 4.0.7 on 2022-09-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_alter_fileupload_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
